# Generated by Django 5.2.1 on 2025-05-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_house_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
