# Generated by Django 5.2.1 on 2025-05-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseRentManagementApp', '0004_userprofile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_No',
            field=models.CharField(max_length=20),
        ),
    ]
